// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHAhOR5mz3KqylKb0G44DPBbSfxy7X00',
    appId: '1:838949661115:web:96796b998c0cdddd51fc9e',
    messagingSenderId: '838949661115',
    projectId: 'webshop-8ff3c',
    authDomain: 'webshop-8ff3c.firebaseapp.com',
    storageBucket: 'webshop-8ff3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuAPereS7VnCgTLG4wxwJ3vTqgFj3GLLA',
    appId: '1:838949661115:android:f8ed3efb33d38af151fc9e',
    messagingSenderId: '838949661115',
    projectId: 'webshop-8ff3c',
    storageBucket: 'webshop-8ff3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnEh49iocvjYPKi_qIfUjj4Tsx_gzqZcM',
    appId: '1:838949661115:ios:dfa7daf258b5e62f51fc9e',
    messagingSenderId: '838949661115',
    projectId: 'webshop-8ff3c',
    storageBucket: 'webshop-8ff3c.appspot.com',
    androidClientId: '838949661115-et8afe1mo0hpsg8bp75bqk5cqgvctjvc.apps.googleusercontent.com',
    iosClientId: '838949661115-n0l0khr4rou96ajm2c7rv80h1h56u00l.apps.googleusercontent.com',
    iosBundleId: 'com.example.projektWebshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnEh49iocvjYPKi_qIfUjj4Tsx_gzqZcM',
    appId: '1:838949661115:ios:f11a0054f205341a51fc9e',
    messagingSenderId: '838949661115',
    projectId: 'webshop-8ff3c',
    storageBucket: 'webshop-8ff3c.appspot.com',
    androidClientId: '838949661115-et8afe1mo0hpsg8bp75bqk5cqgvctjvc.apps.googleusercontent.com',
    iosClientId: '838949661115-frh41ifdpgs8qcskn1n6o2geia39pau1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projektWebshop.RunnerTests',
  );
}
